### ISSUE TITLE
I think it is this, better

### ISSUE THREAD

**Issue by guohuihot** [shagabutdinov/sublime-keymap-enhanced#1]
![aaa](https://cloud.githubusercontent.com/assets/3119995/10709858/0c717658-7a70-11e5-8881-ec77c6ab1fca.jpg)

alt+j  left
alt+ctrl+j left a word
alt+ctrl+shift+j Goto begin of line

alt+l  right
alt+ctrl+l right a word
alt+ctrl+shift+l Goto end of line

alt+i  up
alt+ctrl+i scroll up by 5 lines
alt+ctrl+shift+i Goto begin of file

alt+k  down
alt+ctrl+k scroll down by 5 lines
alt+ctrl+shift+k Goto end of file

alt+h Select by character left
alt+ctrl+h Select by word left
alt+ctrl+shift+h Select begin of line

alt+u del by character left
alt+ctrl+u del by word left
alt+ctrl+shift+u del begin of line
.....

**Comment by shagabutdinov** [comment]
Putting backspace closer arrows is great idea, I like it. And `alt+h` for character selection feels weird for me, why `alt+shift+j` is bad? 

Also I could not change this keymap because it requires a lot of work for rearrange all other plugins keymaps and I'm not ready for; maybe I just got used to my keymaps too much... 

But you can do a fork and put your keymaps to fork. Also try `IndentationNavigation` plugin, it is great addition to overall keyboard navigation. 

Thank you for issue.
